### ISSUE TITLE
Faster CI runners

### ISSUE THREAD

**Issue by LegNeato** [Rust-GPU/rust-gpu#2]
Previously Embark used paid runners to get faster builds. As part of the transition we went to the slower Github action runners. We should look into getting credits and/or sponsors for faster CI if it is a problem.

This is what they used to have:

```yaml
          - os: ubuntu-20.04-16core
            target: x86_64-unknown-linux-gnu
          - os: windows-2022-16core
            target: x86_64-pc-windows-msvc
          - os: macOS-latest-xl
            target: x86_64-apple-darwin
          - os: ubuntu-20.04-16core
            target: aarch64-linux-android
            host: x86_64-unknown-linux-gnu
```
